### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by pombredanne** [metalink-dev/pymetalink#1]
Howdy:
Any reason why pymetalink is GPL and libmetalink is MIT?
Could there be either some homogeneity for licenses, or at least something allowing some linking like an LGPL for the Python library?
Thanks!

**Comment by bneijt** [comment]
Currently the license is decided upon by the principle author and I think most are historically kept the way they are as code patches do not change the licensing.

If you would like a certain part of the metalink ecosystem to have a different license, feel free to file a bug or question for the given project requesting a specific license.

**Comment by pombredanne** [comment]
@bneijt @nabber00 your call of course... In order to be able to use it in Apache-licensed code, I guess I will have to write a ctypes or cffi Python binding for libmetalink or most likely use this one: https://code.launchpad.net/~metalink-dev/pylibmetalink/
It would have been nice to have a pure Python library that can be linked against ...

**Comment by antbryan** [comment]
@nabber00 how do you feel about this? what are the options, a dual license or exceptions?

**Comment by pombredanne** [comment]
FWIW, here are the authors that contributed to this codebase based on the commit logs:
@antbryan  @bneijt  @nabber00  @poeml @tatsuhiro-t @hampus
And an exception or a dual license would be very nice

**Comment by pombredanne** [comment]
FYI in the meantime, I made a clone of pylibmetalink here https://github.com/pombredanne/pylibmetalink though I would mucho prefer this pure Python version here!

**Comment by hampus** [comment]
I think switching to MIT or similar for pylibmetalink might be a good idea. +1 from me if someone wants to look into it.

**Comment by bneijt** [comment]
I've contacted @nabber00 out of thread to see if I can help with whatever decision he makes as he is the principle author and responsible for the licensing if you ask me.

-1 for adding exclusions: I don't like trying to play lawyer.
+1 for whatever nabber00 would like.

Re-opening the issue as it's now a concrete plan.

**Comment by antbryan** [comment]
+1 on @nabber00's wishes, whatever they are.

he's the main author. it does seem like libraries seem to be MIT licensed for broader usage. 

I wonder if @bagder might have some guidance about licensing issues?

**Comment by bagder** [comment]
I think you've already covered the choices you have.

**Comment by nabber00** [comment]
I understand the issue and am considering options.  This code was essentially broken out from Metalink Checker, which is a full brown application under GPL.  I'm not sure that its even functioning completely as expected yet so any feedback (good or bad) is helpful.  If anyone else is interested in how licenses work together I find this is a handy reference:

http://www.dwheeler.com/essays/floss-license-slide.html

**Comment by pombredanne** [comment]
@nabber00 thanks for chiming in. Again, if you do not want to change licensing, that is your call, and I will whip a ctypes binding for the C libmetalink (though lazy as I am, I would rather not ;) )

**Comment by pombredanne** [comment]
FWIW I found an LGPL-licensed lib at http://bazaar.launchpad.net/~registry/celerity/trunk/view/head:/celerity/metalink.py so you do not need to bother if you do not want to. There again, I would much rather use your primary library than reviving dead code...

**Comment by nabber00** [comment]
Hampus has consented and other authors released the GPG.py code under even less restrictive license terms.  I made the change to MIT license with rev #765.  The 6.2 release will also be MIT.

**Comment by pombredanne** [comment]
@hampus @nabber00 Thank you my lords!
