### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'has_key'

### ISSUE THREAD

**Issue by KOLANICH** [metalink-dev/pymetalink#11]
```python
import metalink
l = metalink.Metalink4()
l.parsefile("./5.15.2-0-202011130602qtxmlpatterns-Windows-Windows_7-Mingw-Windows-Windows_7-X86.7z.meta4")
```
https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt5_5152/qt.qt5.5152.win32_mingw81/5.15.2-0-202011130602qtxmlpatterns-Windows-Windows_7-Mingw-Windows-Windows_7-X86.7z.meta4

**Comment by bneijt** [comment]
Ok, so this python code is so old that it's actually not Python 3.x compatible yet.

I removed all has_key references, but you might want to consider that if you are going to use this library in production you might want to get your hands dirty and become a contributor to this repository.

However, thank you for trying the the library and hope you are having fun with Python anyway.

Greetings,

Bram

**Comment by KOLANICH** [comment]
Thank you.
