### ISSUE TITLE
Availability in pip

### ISSUE THREAD

**Issue by Sodki** [metalink-dev/pymetalink#2]
Hi, I've seen a mention of `easy_install` and `pip` on the changelog, but are you planning on having it there soon?

**Comment by nabber00** [comment]
Yes it is in the release notes.  For example on Windows:

C:\Python27\Scripts\pip.exe install https://github.com/metalink-dev/pymetalink/releases/download/v6.2/pymetalink-6.2.zip

**Comment by Sodki** [comment]
I was thinking more along the lines of `pip install pymetalink`. Any plans for that?

**Comment by nabber00** [comment]
No.
