### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by Zeitsperre** [metalink-dev/pymetalink#26]
Hi there,

After the recent QOL changes, I was wondering when a new release might be tagged?

All the best,

**Comment by bneijt** [comment]
Oh, **sorry**, completely forgot to release it.

6.5 is live now, thank you for your contributions!

**Comment by cehbrecht** [comment]
I'm using the new release from conda ... but conda-forge build complains about the version number of pymetalink:
https://github.com/conda-forge/rooki-feedstock/pull/2

```
import: 'rooki'
+ pip check
rooki 0.6.3 has requirement pymetalink>=6.2, but you have pymetalink 0.
WARNING: Tests failed for rooki-0.6.3-pyhd8ed1ab_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: rooki-0.6.3-pyhd8ed1ab_0.conda
```

The version number is "0":
https://github.com/metalink-dev/pymetalink/blob/ba74f9152d22b24e622a09b1d89a0f74631f0d12/pyproject.toml#L7

**Comment by Zeitsperre** [comment]
Hmm... This might be an issue from the conda packaging.

**Comment by Zeitsperre** [comment]
See #28
