### ISSUE TITLE
new release and upload to pypi?

### ISSUE THREAD

**Issue by cehbrecht** [metalink-dev/pymetalink#8]
Can we make a new release? We would like to use `pymetalink` in our released libraries.

**Comment by cehbrecht** [comment]
ping @bneijt

**Comment by bneijt** [comment]
Sorry for the late reply. The project definitely could use some TLC to be honest.

For now I have uploaded 6.2 to pypi but think we should revamp most of the code to make it easier to release. At that point we should have a new release without new features, but the project will be much more maintainable.
